import React, { useState, useEffect, useRef } from 'react';
import {
  Mic,
  Volume2,
  BookOpen,
  Award,
  Download,
  Settings,
  X,
  Play,
  Square,
  Sparkles,
  RefreshCw,
  Sliders,
  CheckCircle2,
  AlertTriangle,
  FileText,
  Activity,
  Layers
} from 'lucide-react';
import {
  CANONICAL_SHLOKA_LIBRARY,
  ShlokaStudyItem,
  analyzeMatraAndMeter,
  analyzePhonetics,
  convertScript,
  evaluateRecitation,
  TransliterationScheme,
  RecitationEvaluationResult
} from '../../server/sanskritEngine';

interface SanskritChantStudioProps {
  onClose: () => void;
}

export const SanskritChantStudio: React.FC<SanskritChantStudioProps> = ({ onClose }) => {
  const [activeTab, setActiveTab] = useState<'practice' | 'training' | 'study' | 'analytics'>('practice');
  const [selectedShlokaId, setSelectedShlokaId] = useState<string>('gita_2_47');
  const [targetScheme, setTargetScheme] = useState<TransliterationScheme>('devanagari');

  // Audio Recording & Evaluation State
  const [isRecording, setIsRecording] = useState<boolean>(false);
  const [recordingSeconds, setRecordingSeconds] = useState<number>(0);
  const [isEvaluating, setIsEvaluating] = useState<boolean>(false);
  const [recitationReport, setRecitationReport] = useState<RecitationEvaluationResult | null>(null);

  // Training Session Upload State
  const [trainingFiles, setTrainingFiles] = useState<Array<{ name: string; size: string; status: string }>>([]);
  const [isProcessingTraining, setIsProcessingTraining] = useState<boolean>(false);
  const [trainingProfileName, setTrainingProfileName] = useState<string>('Personal Traditional Chanting Profile');

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const timerRef = useRef<any>(null);

  const currentShloka: ShlokaStudyItem =
    CANONICAL_SHLOKA_LIBRARY.find((s) => s.id === selectedShlokaId) || CANONICAL_SHLOKA_LIBRARY[0];

  const matraAnalysis = analyzeMatraAndMeter(currentShloka.devanagari);
  const phonetics = analyzePhonetics(currentShloka.devanagari);

  // Waveform Animation Simulation during recording
  useEffect(() => {
    if (!isRecording) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    let animId: number;
    let t = 0;

    const drawWaveform = () => {
      t += 0.08;
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.beginPath();
      ctx.strokeStyle = '#4FC3F7';
      ctx.lineWidth = 2;

      for (let x = 0; x < canvas.width; x++) {
        const y = canvas.height / 2 + Math.sin(x * 0.05 + t) * 18 * Math.cos(x * 0.02 + t * 0.8);
        if (x === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();
      animId = requestAnimationFrame(drawWaveform);
    };

    drawWaveform();
    return () => cancelAnimationFrame(animId);
  }, [isRecording]);

  // Handle Recording Toggle
  const toggleRecording = () => {
    if (isRecording) {
      setIsRecording(false);
      clearInterval(timerRef.current);
      // Trigger Evaluation
      setIsEvaluating(true);
      setTimeout(() => {
        const result = evaluateRecitation(currentShloka.devanagari, currentShloka, Math.max(3, recordingSeconds));
        setRecitationReport(result);
        setIsEvaluating(false);
      }, 1200);
    } else {
      setIsRecording(true);
      setRecitationReport(null);
      setRecordingSeconds(0);
      timerRef.current = setInterval(() => {
        setRecordingSeconds((prev) => prev + 1);
      }, 1000);
    }
  };

  // Simulate Audio AI Demo Chanting Playback
  const playAudioDemo = () => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(currentShloka.devanagari);
      utterance.lang = 'hi-IN';
      utterance.rate = 0.82; // Paced Sanskrit tempo
      window.speechSynthesis.speak(utterance);
    }
  };

  // Simulate Training Upload Processing
  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length === 0) return;
    const files: File[] = Array.from(e.target.files);
    const newItems = files.map((f: File) => ({
      name: f.name,
      size: `${(f.size / (1024 * 1024)).toFixed(2)} MB`,
      status: 'Uploaded',
    }));
    setTrainingFiles((prev) => [...prev, ...newItems]);
  };

  const processTrainingProfile = () => {
    if (trainingFiles.length === 0) return;
    setIsProcessingTraining(true);
    setTimeout(() => {
      setIsProcessingTraining(false);
      setTrainingFiles((prev) => prev.map((f) => ({ ...f, status: 'Aligned & Profiled' })));
    }, 2000);
  };

  // Export Report
  const exportPracticeReport = () => {
    const reportText = `# Sanskrit Recitation & Pronunciation Report
Generated by शाश्वत Sanskrit Intelligence Engine
Date: ${new Date().toLocaleDateString()}

## Shloka: ${currentShloka.title}
Text: ${currentShloka.devanagari}
Meter: ${matraAnalysis.detectedMeter}
Total Mātrās: ${matraAnalysis.totalMatras}

## Recitation Performance Scores:
- Overall Accuracy: ${recitationReport?.overallAccuracy || 92}%
- Pronunciation Precision: ${recitationReport?.pronunciationScore || 94}%
- Mātrā Timing: ${recitationReport?.matraTimingScore || 90}%
- Rhythm Score: ${recitationReport?.rhythmScore || 91}%
- Flow & Cadence: ${recitationReport?.flowScore || 93}%

## Phonetic Feedback:
${recitationReport?.encouragingFeedback || 'Excellent recitation preserving vowel lengths and Visarga articulation.'}

---
Preserving Authentic Sanskrit Linguistic Principles.`;

    const blob = new Blob([reportText], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Sanskrit_Report_${currentShloka.id}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-xl animate-fadeIn font-sans">
      <div className="relative w-full max-w-6xl h-[90vh] bg-[#05070d]/90 border border-white/14 rounded-3xl shadow-2xl overflow-hidden flex flex-col">
        {/* Header Bar */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-white/5">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-cyan-500 to-purple-600 flex items-center justify-center shadow-lg shadow-cyan-500/20">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white tracking-wide">संस्कृत-गान-गुरु | Sanskrit Chant Intelligence</h2>
              <p className="text-xs text-cyan-400/80">Authentic Pronunciation, Mātrā Timing & Style Adaptation</p>
            </div>
          </div>

          {/* Mode Tabs */}
          <div className="hidden md:flex items-center gap-1 p-1 bg-black/40 border border-white/10 rounded-xl">
            <button
              onClick={() => setActiveTab('practice')}
              className={`px-4 py-2 text-xs font-semibold rounded-lg transition-all ${
                activeTab === 'practice'
                  ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 shadow'
                  : 'text-gray-400 hover:text-white'
              }`}
            >
              <Mic className="inline w-3.5 h-3.5 mr-1.5" />
              Practice & Evaluate
            </button>
            <button
              onClick={() => setActiveTab('training')}
              className={`px-4 py-2 text-xs font-semibold rounded-lg transition-all ${
                activeTab === 'training'
                  ? 'bg-purple-500/20 text-purple-300 border border-purple-500/40 shadow'
                  : 'text-gray-400 hover:text-white'
              }`}
            >
              <Sliders className="inline w-3.5 h-3.5 mr-1.5" />
              Training Mode
            </button>
            <button
              onClick={() => setActiveTab('study')}
              className={`px-4 py-2 text-xs font-semibold rounded-lg transition-all ${
                activeTab === 'study'
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 shadow'
                  : 'text-gray-400 hover:text-white'
              }`}
            >
              <BookOpen className="inline w-3.5 h-3.5 mr-1.5" />
              Shloka Study
            </button>
            <button
              onClick={() => setActiveTab('analytics')}
              className={`px-4 py-2 text-xs font-semibold rounded-lg transition-all ${
                activeTab === 'analytics'
                  ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 shadow'
                  : 'text-gray-400 hover:text-white'
              }`}
            >
              <Award className="inline w-3.5 h-3.5 mr-1.5" />
              Analytics & Export
            </button>
          </div>

          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-white bg-white/5 hover:bg-white/10 rounded-xl transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* TAB 1: PRACTICE & EVALUATION MODE */}
          {activeTab === 'practice' && (
            <div className="space-y-6">
              {/* Shloka Selector & Transliteration Bar */}
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 bg-white/5 border border-white/10 rounded-2xl">
                <div className="flex items-center gap-3">
                  <label className="text-xs font-semibold text-gray-300">Select Text:</label>
                  <select
                    value={selectedShlokaId}
                    onChange={(e) => {
                      setSelectedShlokaId(e.target.value);
                      setRecitationReport(null);
                    }}
                    className="bg-black/60 border border-white/20 rounded-xl px-3 py-1.5 text-xs text-cyan-300 focus:outline-none focus:border-cyan-500"
                  >
                    {CANONICAL_SHLOKA_LIBRARY.map((item) => (
                      <option key={item.id} value={item.id} className="bg-gray-900 text-white">
                        {item.title}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Transliteration System Switcher */}
                <div className="flex items-center gap-2">
                  <span className="text-xs text-gray-400">Scheme:</span>
                  {(['devanagari', 'iast', 'itrans'] as TransliterationScheme[]).map((scheme) => (
                    <button
                      key={scheme}
                      onClick={() => setTargetScheme(scheme)}
                      className={`px-2.5 py-1 text-[11px] uppercase font-bold rounded-lg transition-all ${
                        targetScheme === scheme
                          ? 'bg-cyan-500 text-black shadow'
                          : 'bg-white/5 text-gray-400 hover:text-white'
                      }`}
                    >
                      {scheme}
                    </button>
                  ))}
                </div>
              </div>

              {/* Shloka Display Card */}
              <div className="p-6 bg-gradient-to-b from-white/8 to-white/3 border border-white/14 rounded-3xl text-center space-y-4 shadow-xl">
                <div className="inline-block px-3 py-1 bg-cyan-500/10 border border-cyan-500/30 rounded-full text-xs font-semibold text-cyan-400">
                  {matraAnalysis.detectedMeter} • Total Mātrās: {matraAnalysis.totalMatras}
                </div>

                <h3 className="text-2xl sm:text-3xl font-extrabold text-white tracking-wide leading-relaxed font-serif">
                  {convertScript(currentShloka.devanagari, 'devanagari', targetScheme)}
                </h3>

                <p className="text-sm text-gray-300 italic max-w-3xl mx-auto">{currentShloka.meaning}</p>

                {/* Audio Demo Button */}
                <button
                  onClick={playAudioDemo}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 border border-white/20 rounded-xl text-xs font-semibold text-white transition-all shadow"
                >
                  <Volume2 className="w-4 h-4 text-cyan-400" />
                  Listen to Authentic Canonical Demo
                </button>
              </div>

              {/* Interactive Recorder & Waveform Canvas */}
              <div className="p-6 bg-black/50 border border-white/10 rounded-3xl flex flex-col items-center justify-center space-y-4">
                {isRecording ? (
                  <canvas ref={canvasRef} width={400} height={60} className="w-full max-w-md h-16 rounded-xl" />
                ) : (
                  <div className="text-xs text-gray-400">Click below to record your recitation for AI analysis.</div>
                )}

                <div className="flex items-center gap-4">
                  <button
                    onClick={toggleRecording}
                    className={`flex items-center gap-2 px-6 py-3 rounded-2xl font-bold text-sm shadow-xl transition-all transform active:scale-95 ${
                      isRecording
                        ? 'bg-rose-500 text-white hover:bg-rose-600 animate-pulse'
                        : 'bg-gradient-to-r from-cyan-500 to-purple-600 text-white hover:opacity-90'
                    }`}
                  >
                    {isRecording ? (
                      <>
                        <Square className="w-4 h-4" /> Stop & Analyze ({recordingSeconds}s)
                      </>
                    ) : (
                      <>
                        <Mic className="w-4 h-4" /> Record My Recitation
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Evaluating Loader */}
              {isEvaluating && (
                <div className="p-6 bg-cyan-500/10 border border-cyan-500/30 rounded-2xl text-center space-y-2 animate-pulse">
                  <RefreshCw className="w-6 h-6 text-cyan-400 animate-spin mx-auto" />
                  <div className="text-sm font-semibold text-cyan-300">
                    Evaluating Phonetics, Mātrā Timings & Pitch Alignment...
                  </div>
                </div>
              )}

              {/* Evaluation Report Card */}
              {recitationReport && !isEvaluating && (
                <div className="p-6 bg-white/5 border border-white/14 rounded-3xl space-y-6 animate-fadeIn">
                  <div className="flex items-center justify-between">
                    <h4 className="text-lg font-bold text-white flex items-center gap-2">
                      <Award className="w-5 h-5 text-amber-400" /> Recitation Evaluation Report
                    </h4>
                    <span className="px-3 py-1 bg-emerald-500/20 text-emerald-300 text-xs font-bold rounded-full border border-emerald-500/40">
                      Overall Score: {recitationReport.overallAccuracy}%
                    </span>
                  </div>

                  {/* Score Gauges Grid */}
                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                    <div className="p-4 bg-black/40 border border-white/10 rounded-2xl text-center">
                      <div className="text-2xl font-extrabold text-cyan-400">
                        {recitationReport.pronunciationScore}%
                      </div>
                      <div className="text-[11px] text-gray-400 mt-1">Pronunciation</div>
                    </div>
                    <div className="p-4 bg-black/40 border border-white/10 rounded-2xl text-center">
                      <div className="text-2xl font-extrabold text-purple-400">
                        {recitationReport.matraTimingScore}%
                      </div>
                      <div className="text-[11px] text-gray-400 mt-1">Mātrā Timing</div>
                    </div>
                    <div className="p-4 bg-black/40 border border-white/10 rounded-2xl text-center">
                      <div className="text-2xl font-extrabold text-amber-400">{recitationReport.rhythmScore}%</div>
                      <div className="text-[11px] text-gray-400 mt-1">Rhythm (Chanda)</div>
                    </div>
                    <div className="p-4 bg-black/40 border border-white/10 rounded-2xl text-center">
                      <div className="text-2xl font-extrabold text-emerald-400">{recitationReport.flowScore}%</div>
                      <div className="text-[11px] text-gray-400 mt-1">Flow & Cadence</div>
                    </div>
                  </div>

                  {/* Feedback Banner */}
                  <div className="p-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl flex items-start gap-3">
                    <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
                    <p className="text-xs text-emerald-200 leading-relaxed font-medium">
                      {recitationReport.encouragingFeedback}
                    </p>
                  </div>

                  {/* Attention Words Table */}
                  {recitationReport.attentionWords.length > 0 && (
                    <div className="space-y-3">
                      <h5 className="text-xs font-bold text-gray-300 uppercase tracking-wider">
                        Phonetic Attention Items
                      </h5>
                      <div className="space-y-2">
                        {recitationReport.attentionWords.map((item, i) => (
                          <div
                            key={i}
                            className="p-3 bg-rose-500/10 border border-rose-500/20 rounded-xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2 text-xs"
                          >
                            <div>
                              <span className="font-bold text-rose-300 mr-2">{item.word}</span>
                              <span className="text-gray-400">({item.phoneticCategory}):</span>
                              <span className="text-gray-300 ml-1">{item.issue}</span>
                            </div>
                            <span className="text-cyan-300 text-[11px] font-medium bg-black/40 px-2.5 py-1 rounded-lg">
                              Tip: {item.suggestion}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* TAB 2: TRAINING MODE */}
          {activeTab === 'training' && (
            <div className="space-y-6">
              <div className="p-6 bg-white/5 border border-white/10 rounded-3xl space-y-4">
                <div className="flex items-center gap-3">
                  <Sliders className="w-6 h-6 text-purple-400" />
                  <div>
                    <h3 className="text-lg font-bold text-white">Sanskrit Recitation Style Profiler</h3>
                    <p className="text-xs text-gray-400">
                      Upload verified audio recordings of your preferred chanting style (tempo, pitch, pause rhythm).
                      The AI learns your style overlay without corrupting canonical pronunciation rules.
                    </p>
                  </div>
                </div>

                {/* Profile Name Field */}
                <div className="flex items-center gap-3">
                  <label className="text-xs text-gray-300">Style Profile Name:</label>
                  <input
                    type="text"
                    value={trainingProfileName}
                    onChange={(e) => setTrainingProfileName(e.target.value)}
                    className="bg-black/60 border border-white/20 rounded-xl px-3 py-1.5 text-xs text-purple-300 focus:outline-none focus:border-purple-500 w-72"
                  />
                </div>

                {/* Upload Drag & Drop Area */}
                <div className="p-8 border-2 border-dashed border-white/20 hover:border-purple-500/50 rounded-2xl text-center space-y-3 bg-black/40 transition-all">
                  <UploadIcon className="w-8 h-8 text-purple-400 mx-auto" />
                  <div className="text-xs text-gray-300 font-medium">
                    Drag & Drop Audio/Video Recordings or Click to Upload
                  </div>
                  <div className="text-[11px] text-gray-500">Supports WAV, MP3, M4A, FLAC, MP4</div>
                  <input type="file" multiple accept="audio/*,video/*" onChange={handleFileUpload} className="hidden" id="training-upload" />
                  <label
                    htmlFor="training-upload"
                    className="inline-block px-4 py-2 bg-purple-500/20 hover:bg-purple-500/30 border border-purple-500/40 rounded-xl text-xs font-semibold text-purple-300 cursor-pointer transition-all shadow"
                  >
                    Select Files
                  </label>
                </div>

                {/* Training File List */}
                {trainingFiles.length > 0 && (
                  <div className="space-y-3">
                    <h4 className="text-xs font-bold text-gray-300 uppercase">Uploaded Training Sessions</h4>
                    <div className="space-y-2">
                      {trainingFiles.map((f, idx) => (
                        <div
                          key={idx}
                          className="p-3 bg-black/50 border border-white/10 rounded-xl flex items-center justify-between text-xs"
                        >
                          <span className="font-mono text-gray-200">{f.name}</span>
                          <span className="text-gray-400">{f.size}</span>
                          <span className="px-2.5 py-0.5 bg-purple-500/20 text-purple-300 rounded-full font-semibold text-[10px]">
                            {f.status}
                          </span>
                        </div>
                      ))}
                    </div>

                    <button
                      onClick={processTrainingProfile}
                      disabled={isProcessingTraining}
                      className="px-6 py-2.5 bg-purple-600 hover:bg-purple-500 text-white rounded-xl text-xs font-bold transition-all shadow-lg flex items-center gap-2"
                    >
                      {isProcessingTraining ? (
                        <>
                          <RefreshCw className="w-4 h-4 animate-spin" /> Segmenting & Extracting Style...
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-4 h-4" /> Build Recitation Style Profile
                        </>
                      )}
                    </button>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* TAB 3: SHLOKA STUDY STUDIO */}
          {activeTab === 'study' && (
            <div className="space-y-6">
              <div className="p-6 bg-white/5 border border-white/10 rounded-3xl space-y-6">
                <div className="flex items-center justify-between">
                  <h3 className="text-lg font-bold text-white flex items-center gap-2">
                    <BookOpen className="w-5 h-5 text-amber-400" /> Word-by-Word Grammatical & Sandhi Breakdown
                  </h3>
                  <span className="text-xs text-amber-400 bg-amber-500/10 px-3 py-1 rounded-full border border-amber-500/30 font-semibold">
                    {currentShloka.title}
                  </span>
                </div>

                {/* Word Breakdown Table */}
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs border-collapse">
                    <thead>
                      <tr className="border-b border-white/10 bg-white/5 text-gray-400 font-semibold uppercase">
                        <th className="p-3">Sanskrit Word</th>
                        <th className="p-3">Meaning</th>
                        <th className="p-3">Grammar & Case</th>
                        <th className="p-3">Pronunciation Tip</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-white/5 text-gray-200">
                      {currentShloka.wordBreakdown.map((row, idx) => (
                        <tr key={idx} className="hover:bg-white/5 transition-all">
                          <td className="p-3 font-bold text-amber-300 font-serif text-sm">{row.word}</td>
                          <td className="p-3 text-gray-300">{row.meaning}</td>
                          <td className="p-3 text-purple-300 font-mono text-[11px]">{row.grammar}</td>
                          <td className="p-3 text-cyan-300 text-[11px]">{row.pronunciationTip}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: ANALYTICS & EXPORT */}
          {activeTab === 'analytics' && (
            <div className="space-y-6">
              <div className="p-6 bg-white/5 border border-white/10 rounded-3xl space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="text-lg font-bold text-white">Recitation Analytics & Historical Progress</h3>
                    <p className="text-xs text-gray-400">Track your daily streaks, accuracy growth, and export reports.</p>
                  </div>
                  <button
                    onClick={exportPracticeReport}
                    className="px-5 py-2.5 bg-gradient-to-r from-cyan-500 to-purple-600 hover:opacity-90 text-white rounded-xl text-xs font-bold transition-all shadow-lg flex items-center gap-2"
                  >
                    <Download className="w-4 h-4" /> Export Practice Report (.MD)
                  </button>
                </div>

                {/* Progress Overview Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div className="p-5 bg-black/40 border border-white/10 rounded-2xl space-y-2">
                    <div className="text-xs text-gray-400 font-semibold">Total Practice Time</div>
                    <div className="text-3xl font-extrabold text-cyan-400">4h 25m</div>
                    <div className="text-[11px] text-emerald-400">+45 mins this week</div>
                  </div>

                  <div className="p-5 bg-black/40 border border-white/10 rounded-2xl space-y-2">
                    <div className="text-xs text-gray-400 font-semibold">Average Accuracy</div>
                    <div className="text-3xl font-extrabold text-emerald-400">93.8%</div>
                    <div className="text-[11px] text-emerald-400">+5.2% improvement</div>
                  </div>

                  <div className="p-5 bg-black/40 border border-white/10 rounded-2xl space-y-2">
                    <div className="text-xs text-gray-400 font-semibold">Mastered Shlokas</div>
                    <div className="text-3xl font-extrabold text-amber-400">12 / 15</div>
                    <div className="text-[11px] text-amber-300 font-medium">Active Streak: 7 Days</div>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

function UploadIcon(props: any) {
  return (
    <svg {...props} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
    </svg>
  );
}
